
services:
  blog-db:
    image: postgres:17
    ports:
      - 9004:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 3s
      timeout: 60s
      retries: 5
  blog-db-init:
    build:
      dockerfile: services/blog/Dockerfile.db-init
    working_dir: /sandbox3-go
    volumes:
      - ./:/sandbox3-go:rw
    command: sh -c "cd services/blog && make db-init"
    environment:
      DB_HOST: blog-db
      DB_PORT: "5432"
      DB_NAME: blog
      DB_PASSWORD: root
      DB_USER: root
    depends_on:
      blog-db:
        condition: service_healthy
        restart: true
  blog-db-init-loc:
    image: golang:1.23.4
    working_dir: /sandbox3-go
    volumes:
      - ./:/sandbox3-go:rw
    command: sh -c "cd services/blog && make db-init-loc"
    environment:
      GOTOOLCHAIN: auto
      DB_HOST: blog-db
      DB_PORT: "5432"
      DB_NAME: blog
      DB_PASSWORD: root
      DB_USER: root
    depends_on:
      blog-db-init:
        condition: service_completed_successfully
        restart: true
  blog-server-loc:
    image: golang:1.23.4
    working_dir: /sandbox3-go
    volumes:
      - ./:/sandbox3-go:rw
    ports:
      - 9001:8080
    command: sh -c "cd services/blog && make server-init-loc"
    environment:
      GOTOOLCHAIN: auto
      ENV: loc
      PORT: "8080"
      SITE_ORIGIN: http://localhost:9001
      GOOGLE_TAG_MANAGER_ID: dummy_tag_id
      ADMIN_TOKEN: dummy_admin_token
      DIR_PATH_HTML_TEMPLATE: go/internal/web
      DIR_PATH_CSS: go/internal/web/_css
      LOG_LEVEL: debug
      LOGGER_TYPE: devslog
      DB_HOST: blog-db
      DB_PORT: "5432"
      DB_NAME: blog
      DB_PASSWORD: root
      DB_USER: root
    depends_on:
      blog-db-init-loc:
        condition: service_completed_successfully
        restart: true
  blog-db-init-test:
    build:
      dockerfile: services/blog/Dockerfile.db-init
    working_dir: /sandbox3-go
    volumes:
      - ./:/sandbox3-go:rw
    command: sh -c "cd services/blog && make db-init"
    environment:
      DB_HOST: blog-db
      DB_PORT: "5432"
      DB_NAME: blog_test
      DB_PASSWORD: root
      DB_USER: root
    depends_on:
      blog-db:
        condition: service_healthy
        restart: true
  blog-test:
    build:
      dockerfile: services/blog/Dockerfile.test
    working_dir: /sandbox3-go
    volumes:
      - ./:/sandbox3-go:rw
    ports:
      - 9003:8080
    command: sh -c "cd services/blog && make test merge-test-report"
    depends_on:
      blog-db:
        condition: service_healthy
      blog-db-init-test:
        condition: service_completed_successfully
