
services:
  blog-server:
    image: golang:1.23.4
    working_dir: /sandbox3-go
    volumes:
      - ./:/sandbox3-go:rw
    ports:
      - 9001:8080
    command: sh -c "cd services/blog && make init-server"
    depends_on:
      blog-db:
        condition: service_healthy
  blog-db:
    image: mysql:8.4.0-oraclelinux8
    volumes:
      - ./services/blog/db/etc/mysql/conf.d:/etc/mysql/conf.d:ro
    ports:
      - 9002:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 3s
      timeout: 60s
      retries: 5
