
services:
  blog-db:
    image: mysql:8.4.0-oraclelinux8
    volumes:
      - ./services/blog/db/etc/mysql/conf.d:/etc/mysql/conf.d:ro
    ports:
      - 9002:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 3s
      timeout: 60s
      retries: 5
  blog-server-loc:
    image: golang:1.23.4
    working_dir: /sandbox3-go
    volumes:
      - ./:/sandbox3-go:rw
    ports:
      - 9001:8080
    command: sh -c "cd services/blog && make server-init-loc"
    depends_on:
      blog-db:
        condition: service_healthy
  blog-test:
    build:
      dockerfile: services/blog/Dockerfile.test
    working_dir: /sandbox3-go
    volumes:
      - ./:/sandbox3-go:rw
    ports:
      - 9003:8080
    command: sh -c "cd services/blog && make test merge-test-report"
    environment:
      SITE_ORIGIN: http://localhost:9003
      GOOGLE_TAG_MANAGER_ID: dummy_tag_id
      ADMIN_TOKEN: dummy_admin_token
      DIR_PATH_HTML_TEMPLATE: go/internal/web
      DIR_PATH_CSS: go/internal/web/_css
    depends_on:
      blog-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 3s
      timeout: 60s
      retries: 5
