// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: articles.test.sql

package sqlcgo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateArticlesForTestParams struct {
	ID          pgtype.UUID
	Title       string
	Published   bool
	PublishedAt pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
