// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: articles.sql

package sqlcgo

import (
	"context"

	"github.com/google/uuid"
)

const getArticle = `-- name: GetArticle :one
SELECT id FROM articles
`

func (q *Queries) GetArticle(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getArticle)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
