// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: articles.sql

package sqlcgo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticle = `-- name: GetArticle :one
SELECT id FROM articles
`

func (q *Queries) GetArticle(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getArticle)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
