// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgo

import (
	"database/sql"
	"time"
)

type Article struct {
	ID          string
	Title       string
	Published   bool
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ArticlesSearchIndex struct {
	ArticleID   string
	Tags        sql.NullString
	Published   bool
	CreatedAt   time.Time
	PublishedAt sql.NullTime
}

type File struct {
	ID        string
	Type      string
	MediaType sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FileThumbnail struct {
	ID        string
	FileID    string
	MediaType sql.NullString
}

type MappingArticlesTag struct {
	ArticleID string
	TagID     string
}

type Tag struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
