// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          pgtype.UUID
	Title       string
	Published   bool
	PublishedAt pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type ArticlesSearchIndex struct {
	ArticleID   pgtype.UUID
	Tags        pgtype.Text
	Published   bool
	PublishedAt pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type File struct {
	ID        pgtype.UUID
	Name      string
	Type      int16
	MediaType pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type FileThumbnail struct {
	ID        pgtype.UUID
	FileID    pgtype.UUID
	MediaType pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type RelArticlesTag struct {
	ArticleID pgtype.UUID
	TagID     pgtype.UUID
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
