// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tags.sql

package sqlcgo

import (
	"context"

	"github.com/google/uuid"
)

const readTagIDByName = `-- name: ReadTagIDByName :one
SELECT id FROM tags WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) ReadTagIDByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, readTagIDByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
