// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: articles.sql

package sqlcgo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateArticlesParams struct {
	ID          uuid.UUID
	Title       string
	PublishedAt pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

const deleteArticlesPhysically = `-- name: DeleteArticlesPhysically :exec
DELETE FROM articles
`

func (q *Queries) DeleteArticlesPhysically(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteArticlesPhysically)
	return err
}
