// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tags.sql

package sqlcgo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateTagsParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

const deleteTagsPhysically = `-- name: DeleteTagsPhysically :exec
DELETE FROM tags
`

func (q *Queries) DeleteTagsPhysically(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteTagsPhysically)
	return err
}
