CREATE TABLE IF NOT EXISTS articles (
    id UUID PRIMARY KEY NOT NULL,
    title VARCHAR(25) NOT NULL,
    published_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tags (
    id UUID PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_tags_name ON tags (name);

CREATE TABLE IF NOT EXISTS rel_articles_tags (
    article_id UUID NOT NULL REFERENCES articles(id) ON DELETE RESTRICT,
    tag_id UUID NOT NULL REFERENCES tags(id) ON DELETE RESTRICT,
    PRIMARY KEY (article_id, tag_id)
);

CREATE TABLE IF NOT EXISTS articles_search_indices (
    article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    tag_ids UUID[],
    published_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id)
);

CREATE TABLE IF NOT EXISTS files (
    id UUID PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    type SMALLINT NOT NULL,
    media_type TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS file_thumbnails (
    id UUID PRIMARY KEY NOT NULL,
    file_id UUID NOT NULL REFERENCES files(id) ON DELETE RESTRICT,
    media_type TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);
