// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rel_articles_tags.sql

package sqlcgo

import (
	"github.com/google/uuid"
)

type CreateRelArticlesTagsParams struct {
	ArticleID uuid.UUID
	TagID     uuid.UUID
}
