on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/blog
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up blog-test
      - run: mkdir ga_artifacts && cp gocov.html ga_artifacts/ && cp gocovfunc.txt ga_artifacts/
      - uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: services/blog/ga_artifacts
      - run: sh ../../fail-if-coverage-unsatisfied.sh 80
